name: Check

on: push

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16.18
          cache: yarn
      - name: install
        run: |
          git config --global url."https://github.com/".insteadOf git@github.com:
          git config --global url."https://".insteadOf git://
          yarn install
      - name: build
        run: yarn run build --concurrency=1
      - name: lint
        run: yarn run lint
      - name: test
        run: yarn run test
