name: Check

on: push

jobs:
  check:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16.18
          cache: yarn
      - name: install
        run: |
          git config --global url."https://github.com/".insteadOf git@github.com:
          git config --global url."https://".insteadOf git://
          yarn install
      - name: lint
        run: yarn run lint
      - name: build
        run: yarn run build
      - name: test
        run: yarn run test
      - name: Archive production webext artifacts chrome
        uses: actions/upload-artifact@v3
        with:
          name: dist-webext-chrome
          path: |
            ./apps/webext/dist/chrome/*
      - name: Archive production webext artifacts firefox
        uses: actions/upload-artifact@v3
        with:
          name: dist-webext-firefox
          path: |
            ./apps/webext/dist/firefox/*
