name: Release

env:
  DIRECTORY: dist

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version"
        required: true

jobs:
  Submit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: npm
      - name: install
        run: npm ci || npm install
      - run: npm run build --if-present
      - name: Create release
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            await github.request(`POST /repos/${{ github.repository }}/releases`, {
              tag_name: "${{ github.event.inputs.version }}"",
              generate_release_notes: true
            });
      - name: Submit
        run: |
          cd $DIRECTORY/chrome && npx chrome-webstore-upload-cli@2 upload
        env:
          EXTENSION_ID: ${{ secrets.EXTENSION_ID }}
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          REFRESH_TOKEN: ${{ secrets.REFRESH_TOKEN }}
